#!/bin/bash

input=$(wofi --dmenu 2>/dev/null)

[[ -z "$input" ]] && exit 1

length="${input##* }"
flags="${input% *}"
use_digits=0
use_letters=0
use_capitals=0

[[ "$flags" =~ [0-9] ]] && use_digits=1
[[ "$flags" =~ [a-z] ]] && use_letters=1
[[ "$flags" =~ [A-Z] ]] && use_capitals=1

charset=""
[[ $use_digits -eq 1 ]] && charset+="0-9"
[[ $use_letters -eq 1 ]] && charset+="a-z"
[[ $use_capitals -eq 1 ]] && charset+="A-Z"

if [[ -z "$charset" ]]; then
    echo "Error: No valid character types found in input"
    exit 1
fi

random_string=$(tr -dc "$charset" < /dev/urandom | head -c "$length")

ydotool type -d 0 "$random_string"
